import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import apiClient from '../api/apiClient';
import foodHero from '../assets/food-hero.png';

const CART_STORAGE_KEY = 'ck_cart';
const images = { Burgers: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=85', Chicken: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=700&q=85', Sides: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=700&q=85', Drinks: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=700&q=85' };
const visualPicks = [{ category: 'Pizza', name: 'Fresh oven pizza', imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=700&q=85' }, { category: 'Drinks', name: 'Ice-cold drinks', imageUrl: 'https://images.unsplash.com/photo-1629203849820-fdd70d49c38e?auto=format&fit=crop&w=700&q=85' }];
const reviews = [{ quote: 'Best burger in town! Always hot and super fresh.', name: 'Sarah Khan' }, { quote: 'Delivery is always on time and the food is amazing.', name: 'Ali Raza' }, { quote: 'Their wings are next level — seriously delicious!', name: 'Hina Malik' }];

export default function HomePage() {
  const [products, setProducts] = useState([]);
  useEffect(() => { apiClient.get('/menu', { params: { pageNumber: 1, pageSize: 5 } }).then((res) => setProducts(res.data.items ?? [])).catch(() => {}); }, []);
  function add(product) { const cart = JSON.parse(localStorage.getItem(CART_STORAGE_KEY) ?? '[]'); const existing = cart.find((item) => item.productId === product.id); const next = existing ? cart.map((item) => item.productId === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...cart, { productId: product.id, name: product.name, price: product.price, quantity: 1, imageUrl: product.imageUrl || images[product.category] || foodHero }]; localStorage.setItem(CART_STORAGE_KEY, JSON.stringify(next)); window.dispatchEvent(new Event('storage')); }
  return <main className="home-page"><section className="reference-hero"><div className="reference-hero__copy"><span className="eyebrow">Crispy, fresh & delicious</span><h1>Food worth<br />getting excited<br /><em>about.</em></h1><p>Thoughtfully made burgers, chicken, and sides — delivered hot or ready for pickup.</p><div className="button-row"><Link className="button" to="/menu">Order now <span>→</span></Link><Link className="home-outline" to="/menu">View menu</Link></div><div className="home-rating"><strong>★ 4.9</strong><span>★★★★★</span><small>2k+ happy customers</small></div></div><div className="reference-hero__visual"><img src={foodHero} alt="Fresh burger, wings and fries from Crispy Kitchen" /><span className="fresh-tag">♨ <b>Hot & Fresh</b></span></div></section>
    <section className="picks-section"><div className="home-section-head"><div><span className="eyebrow">Popular picks</span><h2>Made for every craving</h2></div><Link to="/menu">View all menu →</Link></div><div className="pick-row">{products.map((product) => <article className="pick-card" key={product.id}><img src={product.imageUrl || images[product.category] || foodHero} alt={product.name} /><span className="pick-category">{product.category}</span><h3>{product.name}</h3><div><strong>${product.price.toFixed(2)}</strong><button onClick={() => add(product)} aria-label={`Add ${product.name}`}>+</button></div></article>)}{visualPicks.map((pick) => <article className="pick-card pick-card--browse" key={pick.category}><img src={pick.imageUrl} alt={pick.name} /><span className="pick-category">{pick.category}</span><h3>{pick.name}</h3><div><Link to="/menu" aria-label={`Browse ${pick.category} on the menu`}>Explore →</Link></div></article>)}</div></section>
    <section className="reference-benefits"><article><i>♨</i><div><small>01</small><h3>Freshly prepared</h3><p>We make every order when you place it.</p></div></article><article><i>⌁</i><div><small>02</small><h3>Pickup or delivery</h3><p>Get your meal your way, right when you need it.</p></div></article><article><i>⌖</i><div><small>03</small><h3>Track every order</h3><p>Know exactly where your food is on its way.</p></div></article></section>
    <section className="delivery-banner"><div><span className="eyebrow">Crispy delivery</span><h2>Fast delivery. Right to your door.</h2><p>Hot, fresh and handled with care.</p></div><Link className="button" to="/menu">Order now →</Link></section>
    <section className="testimonials"><div className="testimonials__head"><span className="eyebrow">What our customers say</span><h2>Loved by thousands</h2></div><div className="review-row">{reviews.map((review) => <article key={review.name}><p>“{review.quote}”</p><div><span className="review-avatar">{review.name[0]}</span><strong>{review.name}</strong><span>★★★★★</span></div></article>)}</div></section></main>;
}
